# Generated by Django 6.0.3 on 2026-03-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('elecciones', models.ManyToManyField(related_name='votantes_habilitados', to='elecciones.eleccion')),
            ],
        ),
    ]
